// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB89UpqYoxOkyJNXC0cR72AgoPEMmoE590',
    appId: '1:98872748062:web:825bcde88bb951eac3e60f',
    messagingSenderId: '98872748062',
    projectId: 'flutter-chat-7a894',
    authDomain: 'flutter-chat-7a894.firebaseapp.com',
    storageBucket: 'flutter-chat-7a894.appspot.com',
    measurementId: 'G-RS2Z1T3C1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANVncs8abPQ93wGchIxEjO9y-HaDw_ssY',
    appId: '1:98872748062:android:01ef35ecabc09779c3e60f',
    messagingSenderId: '98872748062',
    projectId: 'flutter-chat-7a894',
    storageBucket: 'flutter-chat-7a894.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApEBlvYodyuoTUz0ogtqxY0vWT5BP_IVQ',
    appId: '1:98872748062:ios:b8b9579dcadd31ccc3e60f',
    messagingSenderId: '98872748062',
    projectId: 'flutter-chat-7a894',
    storageBucket: 'flutter-chat-7a894.appspot.com',
    iosClientId: '98872748062-fa7tp6nhgujee1encbtnpscdlsopictg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApEBlvYodyuoTUz0ogtqxY0vWT5BP_IVQ',
    appId: '1:98872748062:ios:b8b9579dcadd31ccc3e60f',
    messagingSenderId: '98872748062',
    projectId: 'flutter-chat-7a894',
    storageBucket: 'flutter-chat-7a894.appspot.com',
    iosClientId: '98872748062-fa7tp6nhgujee1encbtnpscdlsopictg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
